# Generated by Django 5.2.6 on 2025-11-09 14:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BrowserSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "browser_type",
                    models.CharField(
                        choices=[
                            ("chromium", "Chromium"),
                            ("firefox", "Firefox"),
                            ("webkit", "WebKit"),
                        ],
                        default="chromium",
                        max_length=20,
                    ),
                ),
                ("playwright_config", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("error", "Error"),
                        ],
                        default="inactive",
                        max_length=20,
                    ),
                ),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("tags", models.JSONField(default=list)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
