# Generated by Django 5.2.6 on 2026-02-12 05:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browsersession', '0002_remove_browsersession_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainThrottleRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(max_length=255)),
                ('delay_seconds', models.FloatField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_throttle_rules', to='browsersession.browsersession')),
            ],
            options={
                'ordering': ['domain'],
                'constraints': [models.UniqueConstraint(fields=('session', 'domain'), name='unique_session_domain')],
            },
        ),
    ]
