# Generated by Django 5.2.6 on 2026-02-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browsersession', '0003_domain_throttle_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='browsersession',
            name='blocked_resource_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='browsersession',
            name='domain_throttle_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='browsersession',
            name='resource_blocking_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
