# Generated by Django 5.2.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("browsersession", "0004_session_settings_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="domainthrottlerule",
            name="enabled",
            field=models.BooleanField(default=False),
        ),
    ]
