# Generated by Django 5.2.6 on 2026-02-26 10:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browsersession', '0005_domainthrottlerule_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowserPool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BrowserPoolSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_sessions', to='browsersession.browserpool')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_memberships', to='browsersession.browsersession')),
            ],
            options={
                'ordering': ['usage_count'],
                'constraints': [models.UniqueConstraint(fields=('pool', 'session'), name='unique_pool_session')],
            },
        ),
        migrations.CreateModel(
            name='BrowserPoolSessionDomainUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(max_length=255)),
                ('usage_count', models.IntegerField(default=0)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_usages', to='browsersession.browserpool')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_domain_usages', to='browsersession.browsersession')),
            ],
            options={
                'ordering': ['usage_count'],
                'constraints': [models.UniqueConstraint(fields=('pool', 'session', 'domain'), name='unique_pool_session_domain')],
            },
        ),
    ]
