# Generated by Django 5.2.6

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browsersession', '0006_add_browser_pool_models'),
    ]

    operations = [
        # Add pool-level settings to BrowserPool
        migrations.AddField(
            model_name='browserpool',
            name='domain_throttle_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='browserpool',
            name='resource_blocking_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='browserpool',
            name='blocked_resource_types',
            field=models.JSONField(blank=True, default=list),
        ),
        # Create PoolDomainThrottleRule
        migrations.CreateModel(
            name='PoolDomainThrottleRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(max_length=255)),
                ('delay_seconds', models.FloatField()),
                ('enabled', models.BooleanField(default=False)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_throttle_rules', to='browsersession.browserpool')),
            ],
            options={
                'ordering': ['domain'],
            },
        ),
        migrations.AddConstraint(
            model_name='pooldomainthrottlerule',
            constraint=models.UniqueConstraint(fields=('pool', 'domain'), name='unique_pool_domain'),
        ),
        # Remove session-level settings from BrowserSession
        migrations.RemoveField(
            model_name='browsersession',
            name='domain_throttle_enabled',
        ),
        migrations.RemoveField(
            model_name='browsersession',
            name='resource_blocking_enabled',
        ),
        migrations.RemoveField(
            model_name='browsersession',
            name='blocked_resource_types',
        ),
        # Remove DomainThrottleRule (session-scoped)
        migrations.DeleteModel(
            name='DomainThrottleRule',
        ),
    ]
