# Generated by Django 5.2.6 on 2025-11-09 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0002_demorequest"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DemoRequest",
        ),
    ]
