# Generated by Django 5.2.6 on 2025-11-09 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("browsersession", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="browsersession",
            name="tags",
        ),
    ]
