# Generated by Django 5.2.6 on 2025-10-05 05:28

from django.db import migrations


def create_node_groups_and_map_nodes(apps, schema_editor):
    """Create NodeGroup instances and map existing StandaloneNode records"""
    NodeGroup = apps.get_model('workflow', 'NodeGroup')
    StandaloneNode = apps.get_model('workflow', 'StandaloneNode')
    
    # Define the mapping from old categories to new node groups
    category_to_group_mapping = {
        'system': {
            'name': 'System Operations',
            'description': 'Core system and workflow control nodes'
        },
        'email': {
            'name': 'Email & Communication',
            'description': 'Email sending, receiving, and communication nodes'
        },
        'database': {
            'name': 'Database Operations',
            'description': 'Database query, insert, update, and management nodes'
        },
        'api': {
            'name': 'API & Integration',
            'description': 'API calls, webhooks, and external service integration nodes'
        },
        'logic': {
            'name': 'Logic & Control Flow',
            'description': 'Conditional logic, branching, and data flow control nodes'
        },
        'control': {
            'name': 'Workflow Control',
            'description': 'Timing, scheduling, and workflow execution control nodes'
        },
        'file': {
            'name': 'File Operations',
            'description': 'File reading, writing, processing, and management nodes'
        }
    }
    
    # Create NodeGroup instances
    created_groups = {}
    for category, group_data in category_to_group_mapping.items():
        node_group, created = NodeGroup.objects.get_or_create(
            name=group_data['name'],
            defaults={
                'description': group_data['description'],
                'is_active': True
            }
        )
        created_groups[category] = node_group
    
    # Map existing StandaloneNode records to NodeGroups
    for node in StandaloneNode.objects.all():
        if node.category in created_groups:
            node.node_group = created_groups[node.category]
            node.save()


def reverse_migration(apps, schema_editor):
    """Reverse the migration by removing node_group assignments"""
    StandaloneNode = apps.get_model('workflow', 'StandaloneNode')
    
    # Clear node_group assignments
    StandaloneNode.objects.update(node_group=None)


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0003_nodegroup_standalonenode_node_group"),
    ]

    operations = [
        migrations.RunPython(
            create_node_groups_and_map_nodes,
            reverse_migration
        ),
    ]
