# Generated by Django 5.2.6 on 2025-10-05 05:41

from django.db import migrations


def ensure_all_nodes_have_node_group(apps, schema_editor):
    """Ensure all StandaloneNode records have a node_group assigned"""
    NodeGroup = apps.get_model('workflow', 'NodeGroup')
    StandaloneNode = apps.get_model('workflow', 'StandaloneNode')
    
    # Get or create a default NodeGroup for nodes without one
    default_group, created = NodeGroup.objects.get_or_create(
        name='Default Group',
        defaults={
            'description': 'Default group for nodes without a specific group',
            'is_active': True
        }
    )
    
    # Assign default group to nodes without a node_group
    nodes_without_group = StandaloneNode.objects.filter(node_group__isnull=True)
    nodes_without_group.update(node_group=default_group)
    
    print(f"Assigned {nodes_without_group.count()} nodes to default group")


def reverse_migration(apps, schema_editor):
    """Reverse migration - no action needed"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0004_auto_20251005_0528"),
    ]

    operations = [
        migrations.RunPython(
            ensure_all_nodes_have_node_group,
            reverse_migration
        ),
    ]
