# Generated by Django 5.2.6 on 2025-10-05 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0005_auto_20251005_0541"),
    ]

    operations = [
        # First, make node_group non-nullable
        migrations.AlterField(
            model_name='standalonenode',
            name='node_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='workflow.nodegroup'),
        ),
        # Then remove the category field
        migrations.RemoveField(
            model_name='standalonenode',
            name='category',
        ),
    ]
