# Generated by Django 5.2.6 on 2025-10-05 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0006_auto_20251005_0542"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="node_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nodes",
                to="workflow.nodetype",
            ),
        ),
    ]
