# Generated by Django 5.2.6 on 2025-10-05 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0007_make_node_type_nullable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="node_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nodes",
                to="workflow.standalonenode",
            ),
        ),
        migrations.DeleteModel(
            name="NodeType",
        ),
    ]
