# Generated by Django 5.2.6 on 2025-10-06 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0012_alter_node_data"),
    ]

    operations = [
        migrations.RenameField(
            model_name="node",
            old_name="node",
            new_name="node_type",
        ),
    ]
