# Generated by Django 5.2.6 on 2025-10-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0014_cleanup_redundant_node_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="form_values",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
