# Generated by Django 5.2.6 on 2025-10-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0015_node_form_values"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="output",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
