# Generated by Django 5.2.6 on 2025-10-08 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0016_node_output"),
    ]

    operations = [
        # Rename position_x to x
        migrations.RenameField(
            model_name='node',
            old_name='position_x',
            new_name='x',
        ),
        # Rename position_y to y
        migrations.RenameField(
            model_name='node',
            old_name='position_y',
            new_name='y',
        ),
        # Remove data field
        migrations.RemoveField(
            model_name='node',
            name='data',
        ),
    ]
