# Generated by Django 5.2.6 on 2025-10-19 21:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0017_rename_position_fields_and_remove_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContainerStats",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cpu_percent", models.FloatField(help_text="CPU usage percentage")),
                ("memory_usage_mb", models.FloatField(help_text="Memory usage in MB")),
                (
                    "memory_percent",
                    models.FloatField(help_text="Memory usage percentage"),
                ),
                ("network_in_kb", models.FloatField(help_text="Network input in KB")),
                ("network_out_kb", models.FloatField(help_text="Network output in KB")),
                ("disk_read_mb", models.FloatField(help_text="Disk read in MB")),
                ("disk_write_mb", models.FloatField(help_text="Disk write in MB")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="container_stats",
                        to="workflow.workflow",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["workflow", "timestamp"],
                        name="workflow_co_workflo_a65d23_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="workflow_co_timesta_2441e4_idx"
                    ),
                ],
            },
        ),
    ]
