# Generated by Django 5.2.6 on 2025-12-18 04:45

from django.db import migrations, models


def copy_node_type_name(apps, schema_editor):
    """Copy StandaloneNode name to the node_type_name field before conversion."""
    Node = apps.get_model('workflow', 'Node')
    for node in Node.objects.all():
        if node.node_type_id:
            try:
                StandaloneNode = apps.get_model('workflow', 'StandaloneNode')
                standalone = StandaloneNode.objects.get(id=node.node_type_id)
                node.node_type_name = standalone.name
            except:
                node.node_type_name = 'unknown'
        else:
            node.node_type_name = 'unknown'
        node.save()


def reverse_copy(apps, schema_editor):
    """Reverse is a no-op since we're just copying data."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0022_demorequest_delete_browsersession"),
    ]

    operations = [
        # Step 1: Add temporary field to store node type name
        migrations.AddField(
            model_name="node",
            name="node_type_name",
            field=models.CharField(max_length=255, default='unknown'),
        ),
        # Step 2: Copy data from StandaloneNode to node_type_name
        migrations.RunPython(copy_node_type_name, reverse_copy),
        # Step 3: Remove the ForeignKey to StandaloneNode
        migrations.RemoveField(
            model_name="standalonenode",
            name="node_group",
        ),
        migrations.RemoveField(
            model_name="node",
            name="node_type",
        ),
        # Step 4: Rename temporary field to node_type
        migrations.RenameField(
            model_name="node",
            old_name="node_type_name",
            new_name="node_type",
        ),
        # Step 5: Handle output -> config migration
        migrations.RemoveField(
            model_name="node",
            name="output",
        ),
        migrations.AddField(
            model_name="node",
            name="config",
            field=models.JSONField(blank=True, default=dict),
        ),
        # Step 6: Delete the models
        migrations.DeleteModel(
            name="NodeGroup",
        ),
        migrations.DeleteModel(
            name="StandaloneNode",
        ),
    ]
