# Generated by Django 5.2.7 on 2025-12-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0023_remove_node_groups_and_standalone_nodes"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="connection",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="connection",
            name="source_handle",
            field=models.CharField(blank=True, default="default", max_length=50),
        ),
        migrations.AlterField(
            model_name="node",
            name="node_type",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="connection",
            unique_together={("source_node", "target_node", "source_handle")},
        ),
    ]
