# Generated by Django 5.2.7 on 2025-12-18 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0025_node_input_data_node_output_data"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContainerStats",
        ),
    ]
