# Generated by Django 5.2.7 on 2025-01-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0026_remove_containerstats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflow",
            name="runs_count",
            field=models.IntegerField(default=0),
        ),
    ]

