# Generated by Django 5.2.7 on 2025-01-23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0027_alter_workflow_runs_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workflow",
            name="success_rate",
        ),
    ]

