# Generated by Django 5.2.6 on 2026-01-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0028_remove_workflow_success_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='workflow_type',
            field=models.CharField(choices=[('production', 'Production Workflow'), ('api', 'API Workflow')], default='production', help_text="Type of workflow: 'production' for continuous/loop-based, 'api' for request-response", max_length=20),
        ),
    ]
