# Generated by Django 5.2.6 on 2025-10-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="category",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="workflow",
            name="created_by",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="workflow",
            name="last_run",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workflow",
            name="next_run",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workflow",
            name="runs_count",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="workflow",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("error", "Error"),
                ],
                default="inactive",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="success_rate",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="workflow",
            name="tags",
            field=models.JSONField(default=list),
        ),
    ]
