# Generated by Django 5.2.6 on 2025-09-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0002_nodetype_workflow_task_id_node_connection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
