# Generated by Django 5.2.6 on 2025-09-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0003_alter_node_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
