# Generated by Django 5.2.6 on 2025-09-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0004_alter_node_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="nodetype",
            name="initiator",
            field=models.BooleanField(default=False),
        ),
    ]
