# Generated by Django 5.2.6 on 2025-09-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0005_nodetype_initiator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nodetype",
            name="initiator",
        ),
        migrations.RemoveField(
            model_name="nodetype",
            name="module_path",
        ),
        migrations.AlterField(
            model_name="node",
            name="data",
            field=models.JSONField(default=dict),
        ),
    ]
