# Generated by Django 5.2.6 on 2025-09-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0006_remove_nodetype_initiator_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nodetype",
            name="config",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="nodetype",
            name="logo",
            field=models.ImageField(default={}, upload_to="node_type_icons"),
            preserve_default=False,
        ),
    ]
