# Generated by Django 5.2.6 on 2025-09-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0007_nodetype_config_nodetype_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nodetype",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="node_type_icons"),
        ),
    ]
