# Generated by Django 5.2.6 on 2025-10-05 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0008_remove_node_type_add_standalone_node"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="node",
            name="node_type",
        ),
        migrations.AddField(
            model_name="node",
            name="node",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workflow_nodes",
                to="workflow.standalonenode",
            ),
        ),
    ]
