# Generated by Django 5.2.6 on 2025-09-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0008_alter_nodetype_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="nodetype",
            name="input",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="nodetype",
            name="output",
            field=models.BooleanField(default=False),
        ),
    ]
