# Generated by Django 5.2.6 on 2025-10-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0009_rename_node_type_to_node"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="data",
            field=models.JSONField(default=dict, null=True),
        ),
    ]
