# Generated by Django 5.2.6 on 2025-09-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0009_nodetype_input_nodetype_output"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflow",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
