# Generated by Django 5.2.6 on 2025-09-26 08:09

import django.db.models.deletion
import uuid
import workflow.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0010_alter_workflow_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="NodeFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.CharField(
                        help_text="Unique key for the file within the node",
                        max_length=255,
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to=workflow.models.node_file_upload_path),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("file_size", models.FloatField(help_text="File size in bytes")),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="workflow.node",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("node", "key")},
            },
        ),
    ]
