# Generated by Django 5.2.6 on 2025-09-26 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0011_nodefile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nodefile",
            name="file_size",
        ),
        migrations.RemoveField(
            model_name="nodefile",
            name="original_filename",
        ),
    ]
