# Generated by Django 5.2.6 on 2025-10-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0011_alter_node_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
