# Generated by Django 5.2.6 on 2025-10-06 17:58

from django.db import migrations


def cleanup_redundant_data(apps, schema_editor):
    """Remove redundant data from Node.data fields"""
    Node = apps.get_model('workflow', 'Node')
    
    # Fields that are redundant and should be removed from data
    redundant_fields = ['name', 'description', 'icon', 'logo', 'category', 'type', 'template_id', 'template_name', 'template_type']
    
    for node in Node.objects.all():
        if node.data:
            # Create a copy of the data
            cleaned_data = dict(node.data)
            
            # Remove redundant fields
            for field in redundant_fields:
                cleaned_data.pop(field, None)
            
            # Only update if data actually changed
            if cleaned_data != node.data:
                node.data = cleaned_data
                node.save(update_fields=['data'])


def reverse_cleanup(apps, schema_editor):
    """Reverse migration - this is not easily reversible"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0013_rename_node_to_node_type"),
    ]

    operations = [
        migrations.RunPython(cleanup_redundant_data, reverse_cleanup),
    ]
