# Generated by Django 5.2.7 on 2025-12-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0024_alter_connection_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="input_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="node",
            name="output_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
