# Generated by Django 5.2.6 on 2025-12-19 06:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleConnectedAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="User-given friendly name like 'Work Account'",
                        max_length=255,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Google account email address", max_length=254
                    ),
                ),
                (
                    "picture",
                    models.URLField(
                        blank=True, help_text="Google profile picture URL", null=True
                    ),
                ),
                (
                    "access_token",
                    models.TextField(help_text="OAuth2 access token for API calls"),
                ),
                (
                    "refresh_token",
                    models.TextField(
                        help_text="OAuth2 refresh token for obtaining new access tokens"
                    ),
                ),
                (
                    "token_expires_at",
                    models.DateTimeField(help_text="When the access token expires"),
                ),
                (
                    "scopes",
                    models.JSONField(
                        default=list, help_text="List of granted OAuth scopes"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this connection is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who owns this Google account connection",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Google Connected Account",
                "verbose_name_plural": "Google Connected Accounts",
                "ordering": ["-created_at"],
                "unique_together": {("user", "email")},
            },
        ),
    ]
