# Generated by Django 5.2.6 on 2026-03-10 07:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Friendly name for the key (e.g. Production script)', max_length=255)),
                ('prefix', models.CharField(db_index=True, help_text='Short prefix for lookup (e.g. toe_abc12)', max_length=16)),
                ('key_hash', models.CharField(help_text='Hashed full key (never store the raw key)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='The user who owns this API key', on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'prefix'), name='unique_user_prefix')],
            },
        ),
    ]
